CREATE TABLE TM_USER (
    USER_NO VARCHAR(32) COMMENT '用户编号(系统生成)',
    CREATED_TIME DATETIME NOT NULL COMMENT '创建时间',
    LAST_MODIFYED_TIME DATETIME NOT NULL COMMENT '修改时间',
    USERNAME VARCHAR(32) NOT NULL COMMENT '用户名',
    PASSWORD VARCHAR(64) NOT NULL COMMENT '密码',
    SALT VARCHAR(32) COMMENT '加密盐',
    HEAD_ICON VARCHAR(64) COMMENT '头像ID',
    USER_STATE VARCHAR(1) COMMENT '用户状态6：冻结，4：激活',
    USER_FLAG VARCHAR(8) COMMENT '用户标识',
    DEL_STATE INT(1) NOT NULL DEFAULT '0' COMMENT '0: 未删除. 1: 已删除',
    UNIQUE KEY(USERNAME),
    PRIMARY KEY (USER_NO)
) COMMENT '用户表';